package event_rules;

import com.ftn.sbnz.model.event.EventEntity;
import com.ftn.sbnz.model.event.EventType;

import com.ftn.sbnz.model.core.visitor.VisitorEntity;
import com.ftn.sbnz.model.core.visitor.VisitorEventPreference;

import com.ftn.sbnz.model.drools_helper.RecommendedEvent;


import java.util.List;


rule "outdoor_events"
    when
        $visitor : VisitorEntity(preferences contains VisitorEventPreference.OUTDOOR_EVENTS)
        $event : RecommendedEvent(event.type == EventType.HIKING || event.type == EventType.CYCLING || event.type == EventType.PICNIC)
    then
        $event.setRecommended(true);
end

rule "culture_events"
    when
        $visitor : VisitorEntity(preferences contains VisitorEventPreference.CULTURAL_EVENTS)
        $event : RecommendedEvent(event.type == EventType.MUSEUM_VISIT || event.type == EventType.GALLERY_VISIT || event.type == EventType.CONCERT)
    then
        $event.setRecommended(true);
end

rule "family_events"
    when
        $visitor : VisitorEntity(preferences contains VisitorEventPreference.FAMILY_EVENTS)
        $event : RecommendedEvent(event.type == EventType.ZOO_VISIT || event.type == EventType.AQUARIUM_VISIT || event.type == EventType.THEME_PARK_VISIT)
    then
        $event.setRecommended(true);
end

rule "sporting_events"
    when
        $visitor : VisitorEntity(preferences contains VisitorEventPreference.SPORTING_EVENTS)
        $event : RecommendedEvent(event.type == EventType.BASKETBALL_GAME || event.type == EventType.FOOTBALL_MATCH || event.type == EventType.BOXING_MATCH)
    then
        $event.setRecommended(true);
end

rule "relaxing_events"
    when
        $visitor : VisitorEntity(preferences contains VisitorEventPreference.RELAXING_EVENTS)
        $event : RecommendedEvent(event.type == EventType.WELLNESS_CENTER || event.type == EventType.SPA_TREATMENT || event.type == EventType.SPA_VISIT)
    then
        $event.setRecommended(true);
end

//=======

rule "local_events"
    when
        $visitor : VisitorEntity()
        $event : RecommendedEvent(event.country.equals($visitor.country))
    then
        $event.setRecommended(true);
end

rule "artistic_events"
    when
        $visitor : VisitorEntity(preferences contains VisitorEventPreference.ARTISTIC_EVENTS)
        $event : RecommendedEvent(event.type == EventType.ART_WORKSHOP || event.type == EventType.ART_LECTURE)
    then
        $event.setRecommended(true);
end

rule "adventure_events"
    when
        $visitor : VisitorEntity(preferences contains VisitorEventPreference.ADVENTURE_EVENTS)
        $event : RecommendedEvent(event.type == EventType.BALLOON_RIDE || event.type == EventType.PARAGLIDING)
    then
        $event.setRecommended(true);
end

rule "exotic_events"
    when
        $visitor : VisitorEntity(preferences contains VisitorEventPreference.EXOTIC_EVENTS)
        $event : RecommendedEvent(event.type == EventType.MICHELIN_STAR_RESTAURANT)
    then
        $event.setRecommended(true);
end

rule "music_multicultural_events"
    when
        $visitor : VisitorEntity(preferences contains VisitorEventPreference.MUSIC_EVENTS)
        $event : RecommendedEvent(event.type == EventType.MULTIPLE_GENRE_CONCERT || event.type == EventType.CONCERT)
    then
        $event.setRecommended(true);
end



