package com.ftn.sbnz.model.event;

public enum EventType {

    HIKING,
    CYCLING,
    PICNIC,
    MUSEUM_VISIT,
    GALLERY_VISIT,
    CONCERT,
    ZOO_VISIT,
    AQUARIUM_VISIT,
    THEME_PARK_VISIT,
    BASKETBALL_GAME,
    FOOTBALL_MATCH,
    BOXING_MATCH,
    WELLNESS_CENTER,
    SPA_TREATMENT,
    SPA_VISIT,
    ART_LECTURE,
    ART_WORKSHOP,
    PARAGLIDING,
    BALLOON_RIDE,
    MICHELIN_STAR_RESTAURANT,
    MULTIPLE_GENRE_CONCERT,
    WINTER_FESTIVAL

}
