package rules.rules_4

import com.ftn.sbnz.model.examples_1.Order;
import com.ftn.sbnz.model.examples_1.OrderLine
import com.ftn.sbnz.model.examples_1.Item
import com.ftn.sbnz.model.examples_1.Person

import java.util.List
import java.util.ArrayList


declare Person
  @PropertyReactive
  name : String
  age : int
end

rule "Name Change Rule"
when
  $person : Person( ) @watch(name)
then
  System.out.println("Person name changed to: " + $person.getName());
end

rule "from"
when
    $o:Order()
    $ol:OrderLine() from $o.getOrderLines()
    $i: Item(name == "notepad") from $ol.getItem()

then
    System.out.println("Order contains notepad item");
end


rule "collect"
when
        $o: Order()
        $olList: List() from collect(OrderLine() from $o.getOrderLines())
then
    List<Item> filteredList = new ArrayList<>();
    for (Object obj : $olList) {
        if (obj instanceof OrderLine) {
            OrderLine ol = (OrderLine) obj;
            if (ol.getItem().getName().equals("notepad")) {
                filteredList.add(ol.getItem());
            }
        }
    }
    System.out.println("Order contains notepad item" + filteredList);
end

rule "Discount on Large Orders"
    when
        $o : Order( total > 50 ) @Watch(total)
    then
        $o.increaseDiscount(10.0); // Increase discount by 10% for orders over $100
        update($o);
end

rule "Special Discount on Specific Item"
    when
        $o : Order()
        $ol : OrderLine( item.name == "notepad" ) @watch(item)
    then
        $o.increaseDiscount(5.0); // Increase discount by 5% for orders containing "notepad"
        update($o);
end

rule "Enable property reactive"
    when
        // Ovo pravilo omogućava property reactive funkcionalnost
        $s: String() from entry-point "enable-property-reactive"
    then
        // Ne radi ništa, samo označava da je property reactive funkcionalnost omogućena
end


